/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biletsistemi;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Tunahan
 */
public class biletler extends javax.swing.JFrame {

    /**
     * Creates new form biletler
     */
    public biletler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Biletleri Göster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("menü");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Yazdır");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        kullanici kullanici = new kullanici();
        String url = "jdbc:derby://localhost:1527/kullanici";
        String veribag = "tuna", sifre= "123";
        String kullaniciadi = kullanici.getkullanici(0);
        try {
            Connection veri = DriverManager.getConnection(url, veribag, sifre);
            System.out.println(kullaniciadi+"dasf");
            String sorgu = "select * from bilet where kullaniciadi='"+ kullaniciadi +"'";
            Statement stat=veri.createStatement();    
            ResultSet rs=stat.executeQuery(sorgu);
            String seferler ="isim \t soyisim \t sehir1 \t sehir2 \t saat \t telefon \t yas \n";
            while(rs.next()){
                String isim = rs.getString("isim");
                String soyisim = rs.getString("soyisim");
                String sehir1 = rs.getString("sehir1");
                String sehir2 = rs.getString("sehir2");
                String saat = rs.getString("saat");
                String telefon = rs.getString("telefon");
                String yas = rs.getString("yas");
                seferler+= isim + "\t" + soyisim + "\t" + sehir1 + "\t" + sehir2 + "\t" + saat + "\t" + telefon + "\t" + yas +"\n";
            }
            jTextArea1.setText(seferler);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Hata"+ ex.toString());
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
             kullanicipanel ucp=new kullanicipanel();
             ucp.setLocationRelativeTo(null);
             ucp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String isim = "";
                String soyisim = "";
                String sehir1 = "";
                String sehir2 = "";
                String saat = "";
                String telefon ="";
                String yas = "";
        
        kullanici kullanici = new kullanici();
        String url = "jdbc:derby://localhost:1527/kullanici";
        String veribag = "tuna", sifre= "123";
        String kullaniciadi = kullanici.getkullanici(0);
        try {
            Connection veri = DriverManager.getConnection(url, veribag, sifre);
            
            String sorgu = "select * from bilet where kullaniciadi='"+ kullaniciadi +"'";
            Statement stat=veri.createStatement();    
            ResultSet rs=stat.executeQuery(sorgu);
           File f=new File("kayit.text");
            while(rs.next()){
                isim = rs.getString("isim");
                soyisim = rs.getString("soyisim");
                sehir1 = rs.getString("sehir1");
                sehir2 = rs.getString("sehir2");
                saat = rs.getString("saat");
                telefon = rs.getString("telefon");
                yas = rs.getString("yas");
                String kayit =isim+soyisim+sehir1+sehir2+saat+telefon+yas;
                        
                        
                        
                try {
            FileWriter fileWriter=new FileWriter(f,true);
            fileWriter.write(kayit);
            fileWriter.close();
            
        }
        catch(IOException e){
            e.printStackTrace();
                } 
                        
                        
                        
                
            }
            
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        String isim = "";
                String soyisim = "";
                String sehir1 = "";
                String sehir2 = "";
                String saat = "";
                String telefon ="";
                String yas = "";
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(biletler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(biletler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(biletler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(biletler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new biletler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
